#include "fabm_driver.h"

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!                                                                        !
!                                                                        !
!     ERGOM model CGT version ported to FABM by Hagen Radtke             !
!     (Leibniz Institute for Baltic Sea Research Warnemünde - IOW).      !
!     Code automatically generated by Code Generation Tool Version <cgt_version> !
!     See www.ergom.net                                                  !
!                                                                        !
!                                                                        !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!-----------------------------------------------------------------------
!BOP
!
! !MODULE: fabm\_iow\_ergom --- Biogeochemical model ERGOM
!
! !INTERFACE:
   module fmi_ergom
!
! !DESCRIPTION:
! Model: <name> Version <version> \\
! <description> \\
! Author(s): <author> \\
! Contact: <contact> \\
! Code generated: <now>
!
! !USES:
   use fabm_types

   implicit none

   private
!
! !PUBLIC MEMBER FUNCTIONS:
   public type_fmi_ergom
!
! !REVISION HISTORY:
!  Author(s):
!
! !PUBLIC_DERIVED_TYPES:
      type,extends(type_base_model) :: type_fmi_ergom
! Variable identifiers
    <tracers vertLoc=WAT>
      type (type_state_variable_id)        :: id_<name>
    </tracers>
    <tracers vertLoc=SED>
      type (type_bottom_state_variable_id) :: id_<name>
    </tracers>
      type (type_dependency_id)            :: id_par,id_ext0,id_temp,id_salt,id_diffusivity
      type (type_horizontal_dependency_id) :: id_par0,id_wind,id_taub,id_surfdiff,id_mld
      type (type_horizontal_dependency_id) :: id_depth, id_lat, id_lon
      type (type_global_dependency_id)     :: id_timestep
      type (type_diagnostic_variable_id)   :: id_dPAR
!      type (type_diagnostic_variable_id)   :: id_dPAR,id_GPP,id_NCP,id_PPR,id_NPR
    <auxiliaries vertLoc=WAT; isOutput=1>
      type (type_diagnostic_variable_id)   :: id_<name>
    </auxiliaries>
    <processes vertLoc=WAT; isOutput=1>
      type (type_diagnostic_variable_id)   :: id_<name>
    </processes>
    <auxiliaries vertLoc=SED; isOutput=1>
      type (type_horizontal_diagnostic_variable_id)   :: id_<name>
    </auxiliaries>
    <processes vertLoc=SED; isOutput=1>
      type (type_horizontal_diagnostic_variable_id)   :: id_<name>
    </processes>
    <auxiliaries vertLoc=SUR; isOutput=1>
      type (type_horizontal_diagnostic_variable_id)   :: id_<name>
    </auxiliaries>
    <processes vertLoc=SUR; isOutput=1>
      type (type_horizontal_diagnostic_variable_id)   :: id_<name>
    </processes>
! Model parameters
    <constants>
      real(rk) :: <name>
    </constants>

! model time step may is stored here preliminarily
      real(rk) :: cgt_timestep

      contains

!     Model procedures
      procedure :: initialize
      procedure :: do
      procedure :: do_bottom
      procedure :: get_light_extinction
      procedure :: do_surface

  end type
!EOP
!-----------------------------------------------------------------------

   CONTAINS

!-----------------------------------------------------------------------
!BOP
!
! !IROUTINE: Initialise the ergom model
!
! !INTERFACE:
pure function theta(x)
!
! !DESCRIPTION:
!   The heavyside step function
!
   IMPLICIT NONE
!
! !INPUT PARAMETERS:
   real(rk), intent(in) :: x
   real(rk)             :: theta
!
!EOP
!-----------------------------------------------------------------------
!BOC
     if (x .gt. 0.0) then
       theta = 1.0
     else
       theta = 0.0
     end if
   END function theta
!EOC

!-----------------------------------------------------------------------
!BOP
!
! !INTERFACE:
pure function power(a,b)
!
! !DESCRIPTION:
!   Generic power function
!
   IMPLICIT NONE
!
! !INPUT PARAMETERS:
   real(rk), intent(in) :: a
   real(rk), intent(in) :: b
   real(rk)             :: power
!
!EOP
!-----------------------------------------------------------------------
!BOC
     power = a**b

   END function power
!EOC

!-----------------------------------------------------------------------
!BOP
!
! !IROUTINE: Initialise the ergom model
!
! !INTERFACE:
subroutine initialize(self,configunit)
!
! !DESCRIPTION:
!   Here, the ergom namelist is read and the variables exported by the model are registered with FABM
!
! !USES
!   List any modules used by this routine.
   IMPLICIT NONE
!
! !INPUT PARAMETERS:
   class (type_fmi_ergom), intent(inout), target :: self
   integer,                intent(in)            :: configunit
!
! !LOCAL VARIABLES:
 <constants>
   real(rk)           :: <name>=<value> ! <description>
 </constants>
 <tracers vertLoc=WAT>
   real(rk)           :: <trimName>_initial=0.0_rk ! <description>
 </tracers>
 <tracers vertLoc=SED>
   real(rk)           :: <trimName>_initial=0.0_rk ! <description>
 </tracers>
   real(rk)           :: cgt_timestep=1.0  ! ecosystem model time step [d]
   real(rk)           :: w_poc_var
   real(rk), parameter:: secs_pr_day=86400.0_rk

!   integer            :: cgt_iteration        ! current number of iteration in the iterative loop
   real(rk)            :: cgt_iteration        ! current number of iteration in the iterative loop

!EOP
!-----------------------------------------------------------------------
!BOC

!  Store parameter values in our own derived type
 <constants>
 call self%get_parameter(self%<name>,'<name>','<units>','<description>',default=<name>)
 </constants>
!  Register state variables
 <tracers vertLoc=WAT>
   call self%get_parameter(<trimName>_initial,'<trimName>_initial','<units>','<description>',default=<trimName>_initial)
 </tracers>
 <tracers vertLoc=SED>
   call self%get_parameter(<trimName>_initial,'<trimName>_initial','<units>','<description>',default=<trimName>_initial)
 </tracers>


!  Register state variables
 <tracers vertLoc=WAT>
   call self%register_state_variable(self%id_<name>,'<trimName>','mol/kg', &
         '<description>', <trimName>_initial &
   <if isPositive=1>
         , minimum=0._rk &
   </if>
   <if vertSpeed/=0>
         , vertical_movement=<vertSpeed>/secs_pr_day &
   </if>
   <if riverDep=1>
         , no_river_dilution=.true. &
   </if>
         )
 </tracers>
 <tracers vertLoc=SED>
   call self%register_state_variable(self%id_<name>,'<trimName>','mol/m**2','<description>', &
         <trimName>_initial &
   <if isPositive=1>
         , minimum=0._rk &
   </if>
         )
 </tracers>

   ! Register the contribution of all state variables to total nitrogen
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_no3, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_nh4, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_spp, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_lpp_fast, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_lpp_slow, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_zoo, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_det, scale_factor=1e6_rk)
   call self%add_to_aggregate_variable(standard_variables%total_nitrogen,self%id_t_cya, scale_factor=1e6_rk)

! Register diagnostic variables
   call self%register_diagnostic_variable(self%id_dPAR,'PAR','W/m**2','photosynthetically active radiation',   &
         output=output_instantaneous)
!   call self%register_diagnostic_variable(self%id_GPP,'GPP','mmol/m**3','gross primary production',            &
!         time_treatment=time_treatment_step_integrated)
!   call self%register_diagnostic_variable(self%id_NCP,'NCP','mmol/m**3','net community production',            &
!         time_treatment=time_treatment_step_integrated)
!   call self%register_diagnostic_variable(self%id_PPR,'PPR','mmol/m**3/d','gross primary production rate',     &
!         time_treatment=time_treatment_averaged)
!   call self%register_diagnostic_variable(self%id_NPR,'NPR','mmol/m**3/d','net community production rate',     &
!         time_treatment=time_treatment_averaged)
! <auxiliaries vertLoc=WAT; isOutput=1>
!   call self%register_diagnostic_variable(self%id_<name>,'<trimName>','1.0','<description>',     &
!        output=output_instantaneous)
!  </auxiliaries>
  <auxiliaries vertLoc=WAT; isOutput=1>
   call self%register_diagnostic_variable(self%id_<name>,'<trimName>','<unit>','<description>',     &
         output=output_instantaneous)
 </auxiliaries>
 <processes vertLoc=WAT; isOutput=1>
   call self%register_diagnostic_variable(self%id_<name>,'<trimName>','mol/kg/d','<description>',     &
         output=output_instantaneous)
 </processes>
 <auxiliaries vertLoc=SED; isOutput=1>
   call self%register_horizontal_diagnostic_variable(self%id_<name>,'<trimName>','1.0','<description>',     &
         output=output_instantaneous,source=source_do_bottom)
 </auxiliaries>
 <processes vertLoc=SED; isOutput=1>
   call self%register_horizontal_diagnostic_variable(self%id_<name>,'<trimName>','mol/kg/d','<description>',     &
         output=output_instantaneous,source=source_do_bottom)
 </processes>
  <auxiliaries vertLoc=SUR; isOutput=1>
   call self%register_horizontal_diagnostic_variable(self%id_<name>,'<trimName>','1.0','<description>',     &
         output=output_instantaneous,source=source_do_surface)
 </auxiliaries>
 <processes vertLoc=SUR; isOutput=1>
   call self%register_horizontal_diagnostic_variable(self%id_<name>,'<trimName>','mol/kg/d','<description>',     &
         output=output_instantaneous,source=source_do_surface)
 </processes>
 
! Register environmental dependencies
   call self%register_dependency(self%id_par,standard_variables%downwelling_photosynthetic_radiative_flux)
   call self%register_dependency(self%id_temp,standard_variables%temperature)
   call self%register_dependency(self%id_salt,standard_variables%practical_salinity)
   call self%register_dependency(self%id_par0,standard_variables%surface_downwelling_photosynthetic_radiative_flux)
   
   call self%register_dependency(self%id_wind,standard_variables%wind_speed)
   call self%register_dependency(self%id_depth,standard_variables%bottom_depth)
   call self%register_dependency(self%id_taub,standard_variables%bottom_stress)
   call self%register_dependency(self%id_lat,standard_variables%latitude)
   call self%register_dependency(self%id_lon,standard_variables%longitude)
   call self%register_dependency(self%id_ext0,standard_variables%attenuation_coefficient_of_photosynthetic_radiative_flux)
   call self%register_dependency(self%id_timestep,type_global_standard_variable(name='timestep',units='s'))
   call self%register_dependency(self%id_diffusivity,type_interior_standard_variable(name='diffusivity',units='m2 s-1'))
   call self%register_dependency(self%id_surfdiff,type_horizontal_standard_variable(name='surfdiff',units='m2 s-1'))
   call self%register_dependency(self%id_mld,type_horizontal_standard_variable(name='mld',units='m'))
   return

   END subroutine initialize
!EOC


!-----------------------------------------------------------------------
!BOP
!
! !IROUTINE: Right hand sides of ergom model
!
! !INTERFACE:
   subroutine do(self,_ARGUMENTS_DO_)
!!
! !USES:
   IMPLICIT NONE
!
! !INPUT PARAMETERS:
   class(type_fmi_ergom), INTENT(IN) :: self
  _DECLARE_ARGUMENTS_DO_
!
!
! !LOCAL VARIABLES:
  <constants>
    real(rk)        :: <name>
  </constants>
  <tracers vertLoc=WAT>
    real(rk)        :: <name>
  </tracers>
  <auxiliaries vertLoc=WAT>
    real(rk)        :: <name>
  </auxiliaries>
  <tracers vertLoc=WAT>
   <limitations>
    real(rk)        :: <name>
   </limitations>
  </tracers>
  <processes vertLoc=WAT>
    real(rk)        :: <name>
  </processes>
    real(rk)        :: cgt_temp
    real(rk)        :: cgt_sali
    real(rk)        :: cgt_light
    real(rk)        :: cgt_lightsurf
    real(rk)        :: cgt_kappa
    real(rk)        :: cgt_density
    real(rk)        :: cgt_longitude
    real(rk)        :: cgt_latitude
    real(rk)        :: cgt_timestep
    real(rk)        :: cgt_diffusivity
    real(rk)        :: cgt_surfdiff
    real(rk)        :: cgt_mld
    real(rk)        :: cgt_bottomdepth
    real(rk)        :: secs_pr_day=86400.0_rk
    real(rk)        :: inv_secs_pr_day
    real(rk)        :: temp1, temp2, temp3, temp4, temp5, &
                       temp6, temp7, temp8, temp9
    real(rk)        :: cgt_iteration        ! current number of iteration in the iterative loop
!EOP
!-----------------------------------------------------------------------
!BOC
!   Store values of constants in local variables
    inv_secs_pr_day = 1.0_rk/secs_pr_day
  <constants>
    <name> = self%<name>
  </constants>

!   Enter spatial_loops (if any)
    _LOOP_BEGIN_

!   Retrieve current (local) state variable values
  <tracers vertLoc=WAT>
    _GET_(self%id_<name>,<name>) !<description>
  </tracers>

!   Retrieve current environmental conditions
    _GET_   (self%id_par,cgt_light)    ! local photosynthetically active radiation
    _GET_HORIZONTAL_(self%id_par0,cgt_lightsurf)    ! local photosynthetically active radiation
    _GET_   (self%id_ext0,cgt_kappa)    ! light attenuation
    _GET_   (self%id_temp,cgt_temp)    !local water temperature
    _GET_   (self%id_salt,cgt_sali)    !local water temperature
    _GET_   (self%id_diffusivity,cgt_diffusivity)    !local tracer diffusivity
    _GET_HORIZONTAL_(self%id_surfdiff,cgt_surfdiff)    !local tracer diffusivity
    _GET_HORIZONTAL_(self%id_mld,cgt_mld)    !local tracer diffusivity
    _GET_GLOBAL_(self%id_timestep,cgt_timestep)    ! integration time step [s]
    _GET_HORIZONTAL_(self%id_lon,cgt_longitude)! Longitude [degE]
    _GET_HORIZONTAL_(self%id_lat,cgt_latitude) ! Latitude  [degN]
    _GET_HORIZONTAL_(self%id_depth,cgt_bottomdepth) !local water depth
    cgt_density = 1035.0_rk               ! Boussinesq density
    cgt_timestep  = cgt_timestep/secs_pr_day  ! ecosystem model time step [d]

!  if ((cgt_longitude .gt. 11.68).and.(cgt_longitude .lt. 11.72)) then 
!  if ((cgt_latitude .gt. 54.83).and.(cgt_latitude .lt. 54.87)) then
   
!  WRITE(*,*) "subroutine do started"
!  WRITE(*,*) "t_dic=",t_dic
 
! endif
! endif
  
! Initialize auxiliaries for iterative loop
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations/=0>
             <name> = <iterInit>
</auxiliaries>

! Iterative loop follows
             do cgt_iteration=1,<maxIterations>
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations/=0>
                if (cgt_iteration .le. <iterations>) then
                   ! <description> :
                   temp1 = <temp1>
                   temp2 = <temp2>
                   temp3 = <temp3>
                   temp4 = <temp4>
                   temp5 = <temp5>
                   temp6 = <temp6>
                   temp7 = <temp7>
                   temp8 = <temp8>
                   temp9 = <temp9>
                   <name> = <formula>
                endif
</auxiliaries>
             enddo

!   Calculation of auxiliary variables (not iterative)
  <auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations=0>
    temp1 = <temp1>
    temp2 = <temp2>
    temp3 = <temp3>
    temp4 = <temp4>
    temp5 = <temp5>
    temp6 = <temp6>
    temp7 = <temp7>
    temp8 = <temp8>
    temp9 = <temp9>
    <name> = <formula>
  </auxiliaries>

!   Calculation of process limitation factors
  <tracers vertLoc=WAT>
    <limitations>
             <name> = <formula>
    </limitations>
  </tracers>

!   Calculation of process rates
  <processes vertLoc=WAT>
    <name> = <turnover>
    ! 23.10
    <name> = max(<name>,0.0)
  </processes>

!   Calculation of late auxiliary variables
  <auxiliaries vertLoc=WAT; calcAfterProcesses=1>
    temp1 = <temp1>
    temp2 = <temp2>
    temp3 = <temp3>
    temp4 = <temp4>
    temp5 = <temp5>
    temp6 = <temp6>
    temp7 = <temp7>
    temp8 = <temp8>
    temp9 = <temp9>
    <name> = <formula>
  </auxiliaries>

!  Applying time tendencies for tracers
<tracers vertLoc=WAT>
  _ADD_SOURCE_(self%id_<name>,0.0 <noNewLine>
    <timeTendencies vertLoc=WAT>
      <timeTendency>*inv_secs_pr_day <noNewLine>
    </timeTendencies>
  )
</tracers>

!  if ((cgt_longitude .gt. 11.68).and.(cgt_longitude .lt. 11.72)) then 
!  if ((cgt_latitude .gt. 54.83).and.(cgt_latitude .lt. 54.87)) then
  
!<tracers name=t_dic>
!  WRITE(*,*) "change_dic=",0.0 <noNewLine>
!    <timeTendencies vertLoc=WAT>
!      <timeTendency>*inv_secs_pr_day <noNewLine>
!    </timeTendencies>
!</tracers>  

!endif
!endif

! Export diagnostic variables
   _SET_DIAGNOSTIC_(self%id_dPAR,cgt_light)
!   _SET_DIAGNOSTIC_(self%id_GPP ,r1/(p1+self%p10)+r2/(p2+self%p20)+r3/(p2+self%p30))
!   _SET_DIAGNOSTIC_(self%id_NCP ,r1/(p1+self%p10)+r2/(p2+self%p20)+r3/(p2+self%p30) - self%lpa*(p1+p2+p3))
!   _SET_DIAGNOSTIC_(self%id_PPR ,(r1/(p1+self%p10)+r2/(p2+self%p20)+r3/(p2+self%p30))*secs_pr_day)
!   _SET_DIAGNOSTIC_(self%id_NPR ,(r1/(p1+self%p10)+r2/(p2+self%p20)+r3/(p2+self%p30) - self%lpa*(p1+p2+p3))*secs_pr_day)
<auxiliaries vertLoc=WAT; isOutput=1>
   _SET_DIAGNOSTIC_(self%id_<name> ,<name>)
</auxiliaries>
<processes vertLoc=WAT; isOutput=1>
   _SET_DIAGNOSTIC_(self%id_<name> ,<name>)
</processes>
!   Leave spatial loops (if any)
   _LOOP_END_

   END subroutine do
!EOC

!-----------------------------------------------------------------------
!BOP
!
! !IROUTINE: Get the light extinction coefficient due to biogeochemical
! variables
!
! !DESCRIPTION:

! !INTERFACE:
   subroutine get_light_extinction(self,_ARGUMENTS_GET_EXTINCTION_)
!
! !INPUT PARAMETERS:
   class (type_fmi_ergom), intent(in) :: self
   _DECLARE_ARGUMENTS_GET_EXTINCTION_
!
! !REVISION HISTORY:
!  Original author(s): Jorn Bruggeman
!
! !LOCAL VARIABLES:
<constants>
   real(rk)                     :: <name>
</constants>
<tracers vertLoc=WAT; opacity/=0>
   real(rk)                     :: <name>
</tracers>

   real(rk)                     :: cgt_density
!EOP
!-----------------------------------------------------------------------
!BOC
   ! Store values of constants in local variables
<constants>
   <name> = self%<name>
</constants>
   cgt_density = 1035.0_rk               ! Boussinesq density
   ! Enter spatial loops (if any)
   _LOOP_BEGIN_

   ! Retrieve current (local) state variable values.

<tracers vertLoc=WAT; opacity/=0>
   _GET_(self%id_<name>,<name>) ! <description>
</tracers>

   ! Self-shading with explicit contribution from background phytoplankton concentration.
   _SET_EXTINCTION_(0.0 <noNewLine>
<tracers vertLoc=WAT; opacity/=0>
                    + <name> * <opacity> * cgt_density <noNewLine>
</tracers>
                   )

   ! Leave spatial loops (if any)
   _LOOP_END_

   end subroutine get_light_extinction
!EOC

!-----------------------------------------------------------------------
!BOP
!
! !IROUTINE:
!
! !INTERFACE:
   subroutine do_bottom(self,_ARGUMENTS_DO_BOTTOM_)
!
! !DESCRIPTION:
! Calculating the benthic fluxes
!
   implicit none

! !INPUT PARAMETERS:
   class (type_fmi_ergom), intent(in) :: self
   _DECLARE_ARGUMENTS_DO_BOTTOM_
!
! !REVISION HISTORY:
!  Original author(s):
!
! !LOCAL VARIABLES:
 <constants>
   real(rk)                   :: <name>
 </constants>
 <tracers vertLoc=WAT>
   real(rk)                   :: <name>
 </tracers>
 <tracers vertLoc=SED>
   real(rk)                   :: <name>
 </tracers>
 <auxiliaries vertLoc=WAT; calcBeforeProcesses=0>
   real(rk)                   :: <name>
 </auxiliaries>
 <auxiliaries vertLoc=SED; calcBeforeProcesses=0>
   real(rk)                   :: <name>
 </auxiliaries>
 <tracers vertLoc=WAT>
  <limitations>
    real(rk)        :: <name>
   </limitations>
 </tracers>
 <tracers vertLoc=SED>
  <limitations>
    real(rk)        :: <name>
   </limitations>
 </tracers>
 <processes vertLoc=SED>
   real(rk)                   :: <name>
 </processes>
   real(rk)                   :: cgt_temp
   real(rk)                   :: cgt_sali
   real(rk)                   :: cgt_light
   real(rk)                   :: cgt_lightsurf
   real(rk)                   :: cgt_kappa   
   real(rk)                   :: cgt_density
   real(rk)                   :: cgt_longitude
   real(rk)                   :: cgt_latitude
   real(rk)                   :: cgt_current_wave_stress
   real(rk)                   :: cgt_bottomdepth
   real(rk)                   :: cgt_timestep
   real(rk)                   :: cgt_diffusivity
   real(rk)                   :: cgt_surfdiff
   real(rk)                   :: cgt_mld
   real(rk)                   :: temp1, temp2, temp3, temp4, temp5, &
                                 temp6, temp7, temp8, temp9
   real(rk)                   :: inv_secs_pr_day
   real(rk)                   :: inv_secs_pr_day_density
   real(rk), parameter        :: secs_pr_day=86400.0_rk
   real(rk)                   :: cgt_iteration        ! current number of iteration in the iterative loop

!EOP
!-----------------------------------------------------------------------
!BOC

   inv_secs_pr_day = 1.0_rk/secs_pr_day
   ! Store values of constants in local variables
   <constants>
      <name> = self%<name>
   </constants>

   ! Enter spatial loops over the horizontal domain (if any).
   _HORIZONTAL_LOOP_BEGIN_

   ! Retrieve abiotic parameters
      _GET_HORIZONTAL_(self%id_taub,cgt_current_wave_stress)
      _GET_HORIZONTAL_(self%id_depth,cgt_bottomdepth) !local water depth
      _GET_HORIZONTAL_(self%id_lon,cgt_longitude)     ! Longitude [degE]
      _GET_HORIZONTAL_(self%id_lat,cgt_latitude)      ! Latitude  [degN]
      _GET_   (self%id_par,cgt_light)    ! local photosynthetically active radiation
      _GET_HORIZONTAL_(self%id_par0,cgt_lightsurf)    ! local photosynthetically active radiation
      _GET_   (self%id_diffusivity,cgt_diffusivity)    !local tracer diffusivity
      _GET_HORIZONTAL_(self%id_surfdiff,cgt_surfdiff)    !local tracer diffusivity
      _GET_HORIZONTAL_(self%id_mld,cgt_mld)    !local tracer diffusivity
      _GET_   (self%id_ext0,cgt_kappa)      
      _GET_   (self%id_temp,cgt_temp)    ! local water temperature
      _GET_   (self%id_salt,cgt_sali)    ! local water salinity
      _GET_GLOBAL_(self%id_timestep,cgt_timestep)    ! integration time step [s]
      cgt_density   = 1035.0_rk          ! Boussinesq density
      cgt_timestep  = cgt_timestep/secs_pr_day  ! ecosystem model time step [d]

      inv_secs_pr_day_density = 1.0_rk/(cgt_density*secs_pr_day)

   ! Retrieve current (local) state variable values.
   <tracers vertLoc=WAT>
      _GET_(self%id_<name>,<name>)
   </tracers>
   <tracers vertLoc=SED>
      _GET_HORIZONTAL_(self%id_<name>,<name>)
   </tracers>

! Initialize auxiliaries for iterative loop
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations/=0>
             <name> = <iterInit>
</auxiliaries>

<auxiliaries vertLoc=SED; calcAfterProcesses=0; iterations/=0>
             <name> = <iterInit>
</auxiliaries>

! Iterative loop follows
             do cgt_iteration=1,<maxIterations>
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations/=0>
                if (cgt_iteration .le. <iterations>) then
                   ! <description> :
                   temp1 = <temp1>
                   temp2 = <temp2>
                   temp3 = <temp3>
                   temp4 = <temp4>
                   temp5 = <temp5>
                   temp6 = <temp6>
                   temp7 = <temp7>
                   temp8 = <temp8>
                   temp9 = <temp9>
                   <name> = <formula>
                endif
</auxiliaries>
<auxiliaries vertLoc=SED; calcAfterProcesses=0; iterations/=0>
                if (cgt_iteration .le. <iterations>) then
                   ! <description> :
                   temp1 = <temp1>
                   temp2 = <temp2>
                   temp3 = <temp3>
                   temp4 = <temp4>
                   temp5 = <temp5>
                   temp6 = <temp6>
                   temp7 = <temp7>
                   temp8 = <temp8>
                   temp9 = <temp9>
                   <name> = <formula>
                endif
</auxiliaries>
             enddo

!   Calculation of auxiliary variables (not iterative)
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations=0>
    temp1 = <temp1>
    temp2 = <temp2>
    temp3 = <temp3>
    temp4 = <temp4>
    temp5 = <temp5>
    temp6 = <temp6>
    temp7 = <temp7>
    temp8 = <temp8>
    temp9 = <temp9>
    <name> = <formula>
</auxiliaries>
<auxiliaries vertLoc=SED; calcAfterProcesses=0; iterations=0>
       temp1 = <temp1>
       temp2 = <temp2>
       temp3 = <temp3>
       temp4 = <temp4>
       temp5 = <temp5>
       temp6 = <temp6>
       temp7 = <temp7>
       temp8 = <temp8>
       temp9 = <temp9>
       <name> = <formula>
</auxiliaries>

   ! Calculate process limitation functions
   <tracers vertLoc=WAT>
     <limitations>
       <name> = <formula>
     </limitations>
   </tracers>
   <tracers vertLoc=SED>
     <limitations>
       <name> = <formula>
     </limitations>
   </tracers>

   ! Calculate process rates
   <processes vertLoc=SED>
       <name> = <turnover>
       ! 23.10
       <name> = max(<name>,0.0)
   </processes>

   ! Apply time tendencies to tracers
   <tracers vertLoc=SED>
      _SET_BOTTOM_ODE_(self%id_<name>,0.0 <noNewLine>
      <timeTendencies>
                    <timeTendency>*inv_secs_pr_day <noNewLine>
      </timeTendencies>
                   )
   </tracers>
   <tracers vertLoc=WAT; hasTimeTendenciesVertLoc=SED>
      _SET_BOTTOM_EXCHANGE_(self%id_<name>,0.0 <noNewLine>
      <timeTendencies vertLoc=SED>
                    <timeTendency2d>*inv_secs_pr_day_density <noNewLine>
      </timeTendencies>
                           )
   </tracers>

    ! Export diagnostic variables
    <processes vertLoc=SED; isOutput=1>
       _SET_HORIZONTAL_DIAGNOSTIC_(self%id_<name> ,<name>)
    </processes>
    <auxiliaries vertLoc=SED; isOutput=1>
       _SET_HORIZONTAL_DIAGNOSTIC_(self%id_<name> ,<name>)
    </auxiliaries>


   ! Leave spatial loops over the horizontal domain (if any).
   _HORIZONTAL_LOOP_END_

   end subroutine do_bottom
!EOC

!-----------------------------------------------------------------------
!BOP
!
! !IROUTINE: Surface fluxes for the ergom model
!
! !INTERFACE:

   subroutine do_surface(self,_ARGUMENTS_DO_SURFACE_)
   class (type_fmi_ergom),intent(in) :: self
   _DECLARE_ARGUMENTS_DO_SURFACE_
!
! !REVISION HISTORY:
!  Original author(s): Hans Burchard, Karsten Bolding
!
! !LOCAL VARIABLES:
! !LOCAL VARIABLES:
 <constants>
   real(rk)                   :: <name>
 </constants>
 <tracers vertLoc=WAT>
   real(rk)                   :: <name>
 </tracers>
 <auxiliaries vertLoc=WAT; calcBeforeProcesses=0>
   real(rk)                   :: <name>
 </auxiliaries>
 <auxiliaries vertLoc=SUR; calcBeforeProcesses=0>
   real(rk)                   :: <name>
 </auxiliaries>
 <tracers vertLoc=WAT>
  <limitations>
   real(rk)                   :: <name>
  </limitations>
 </tracers>
 <processes vertLoc=SUR>
   real(rk)                   :: <name>
 </processes>
   real(rk)                   :: cgt_temp
   real(rk)                   :: cgt_sali
   real(rk)                   :: cgt_light
   real(rk)                   :: cgt_lightsurf
   real(rk)                   :: cgt_kappa
   real(rk)                   :: cgt_density
   real(rk)                   :: cgt_longitude
   real(rk)                   :: cgt_latitude
   real(rk)                   :: cgt_current_wave_stress
   real(rk)                   :: cgt_timestep
   real(rk)                   :: cgt_diffusivity
   real(rk)                   :: cgt_surfdiff
   real(rk)                   :: cgt_mld
   real(rk)                   :: cgt_bottomdepth
   real(rk)                   :: cgt_wind
   real(rk)                   :: temp1, temp2, temp3, temp4, temp5, &
                                 temp6, temp7, temp8, temp9
   real(rk)                   :: inv_secs_pr_day_density
   real(rk), parameter        :: secs_pr_day=86400.0_rk
   real(rk)                   :: cgt_iteration        ! current number of iteration in the iterative loop
!EOP
!-----------------------------------------------------------------------
!BOC
      ! Store values of constants in local variables
   <constants>
      <name> = self%<name>
   </constants>

   ! Enter spatial loops over the horizontal domain (if any).
   _HORIZONTAL_LOOP_BEGIN_

   ! Retrieve abiotic parameters
      _GET_HORIZONTAL_(self%id_taub,cgt_current_wave_stress)
      _GET_   (self%id_par,cgt_light) ! local photosynthetically active radiation
      _GET_HORIZONTAL_(self%id_par0,cgt_lightsurf) ! local photosynthetically active radiation
      _GET_   (self%id_ext0,cgt_kappa)      
      _GET_   (self%id_temp,cgt_temp) !local water temperature
      _GET_   (self%id_salt,cgt_sali) !local water temperature
      _GET_   (self%id_diffusivity,cgt_diffusivity)    !local tracer diffusivity
      _GET_HORIZONTAL_(self%id_surfdiff,cgt_surfdiff)    !local tracer diffusivity
      _GET_HORIZONTAL_(self%id_mld,cgt_mld)    !local tracer diffusivity
      _GET_GLOBAL_(self%id_timestep,cgt_timestep) !integration time step [s]
      _GET_HORIZONTAL_(self%id_lon,cgt_longitude)! Longitude [degE]
      _GET_HORIZONTAL_(self%id_lat,cgt_latitude) ! Latitude  [degN]
      _GET_HORIZONTAL_(self%id_depth,cgt_bottomdepth) !local water depth
      _GET_HORIZONTAL_(self%id_wind,cgt_wind)    !local wind

      cgt_density = 1035.0
      cgt_timestep  = cgt_timestep/secs_pr_day  ! ecosystem model time step [d]

      inv_secs_pr_day_density = 1.0_rk/(cgt_density*secs_pr_day)


   ! Retrieve current (local) state variable values.
   <tracers vertLoc=WAT>
      _GET_(self%id_<name>,<name>)
   </tracers>

   ! Initialize auxiliaries for iterative loop
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations/=0>
             <name> = <iterInit>
</auxiliaries>

<auxiliaries vertLoc=SUR; calcAfterProcesses=0; iterations/=0>
             <name> = <iterInit>
</auxiliaries>
   ! Iterative loop follows
             do cgt_iteration=1,<maxIterations>
<auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations/=0>
                if (cgt_iteration .le. <iterations>) then
                   ! <description> :
                   temp1 = <temp1>
                   temp2 = <temp2>
                   temp3 = <temp3>
                   temp4 = <temp4>
                   temp5 = <temp5>
                   temp6 = <temp6>
                   temp7 = <temp7>
                   temp8 = <temp8>
                   temp9 = <temp9>
                   <name> = <formula>
                endif
</auxiliaries>
<auxiliaries vertLoc=SUR; calcAfterProcesses=0; iterations/=0>
                if (cgt_iteration .le. <iterations>) then
                   ! <description> :
                   temp1 = <temp1>
                   temp2 = <temp2>
                   temp3 = <temp3>
                   temp4 = <temp4>
                   temp5 = <temp5>
                   temp6 = <temp6>
                   temp7 = <temp7>
                   temp8 = <temp8>
                   temp9 = <temp9>
                   <name> = <formula>
                endif
</auxiliaries>
             enddo

   ! Calculate values of auxiliary variables (not iterative)
   <auxiliaries vertLoc=WAT; calcAfterProcesses=0; iterations=0>
       temp1 = <temp1>
       temp2 = <temp2>
       temp3 = <temp3>
       temp4 = <temp4>
       temp5 = <temp5>
       temp6 = <temp6>
       temp7 = <temp7>
       temp8 = <temp8>
       temp9 = <temp9>
       <name> = <formula>
   </auxiliaries>

   <auxiliaries vertLoc=SUR; calcAfterProcesses=0; iterations=0>
       temp1 = <temp1>
       temp2 = <temp2>
       temp3 = <temp3>
       temp4 = <temp4>
       temp5 = <temp5>
       temp6 = <temp6>
       temp7 = <temp7>
       temp8 = <temp8>
       temp9 = <temp9>
       <name> = <formula>
   </auxiliaries>

   ! Calculate process limitation functions
   <tracers vertLoc=WAT>
     <limitations>
       <name> = <formula>
     </limitations>
   </tracers>
!  w_o2_stf =  0.31_8*( sqrt(660.0_8/(1953.4_8 - (128.0_8 - (3.9918_8 - 0.050091_8*cgt_temp)*cgt_temp)*cgt_temp)) )*cgt_wind*cgt_wind*0.24_8 ! needs to be m/d here (0.24 is the factor to convert cm/hr to m/d)
!  w_n2_stf =  0.31_8*( sqrt(660.0_8/(2206.1_8 - (144.86_8 - (4.5413_8 - 0.056988_8*cgt_temp)*cgt_temp)*cgt_temp)) )*cgt_wind*cgt_wind*0.24_8
!  w_co2_stf = 0.31_8*( sqrt(660.0_8/(2073.1_8 - (125.62_8 - (3.6276_8 - 0.043219_8*cgt_temp)*cgt_temp)*cgt_temp)) )*cgt_wind*cgt_wind*0.24_8
   ! Calculate process rates
   <processes vertLoc=SUR>
       <name> = <turnover>
       ! 23.10
       <name> = max(<name>,0.0)
   </processes>

   <auxiliaries vertLoc=SUR; calcAfterProcesses=1; iterations=0>
       temp1 = <temp1>
       temp2 = <temp2>
       temp3 = <temp3>
       temp4 = <temp4>
       temp5 = <temp5>
       temp6 = <temp6>
       temp7 = <temp7>
       temp8 = <temp8>
       temp9 = <temp9>
       <name> = <formula>
   </auxiliaries>
   
   ! Apply time tendencies to tracers
   <tracers vertLoc=WAT; hasTimeTendenciesVertLoc=SUR>
      _ADD_SURFACE_FLUX_(self%id_<name>,0.0 <noNewLine>
      <timeTendencies vertLoc=SUR>
                    <timeTendency2d>*inv_secs_pr_day_density <noNewLine>
      </timeTendencies>
                           )
   </tracers>
    
    ! Export diagnostic variables
    <processes vertLoc=SUR; isOutput=1>
       _SET_HORIZONTAL_DIAGNOSTIC_(self%id_<name> ,<name>)
    </processes>
    <auxiliaries vertLoc=SUR; isOutput=1>
       _SET_HORIZONTAL_DIAGNOSTIC_(self%id_<name> ,<name>)
    </auxiliaries>
   ! Leave spatial loops over the horizontal domain (if any)
   _HORIZONTAL_LOOP_END_

   end subroutine do_surface
!EOC


!-----------------------------------------------------------------------

  END MODULE fmi_ergom

!-----------------------------------------------------------------------
! Copyright by the GOTM-team under the GNU Public License - www.gnu.org
!-----------------------------------------------------------------------
